### ISSUE TITLE
Issues with the latest version of AWS SDK v2

### ISSUE THREAD

**Issue by Kinjalrk2k** [jwerre/secrets#10]
When using the latest version of this package with the latest version of AWS SDK v2, I see the following error:

```
Unexpected end of JSON input
```

After a bit of debugging, I found this was caused by the warning message that AWS SDK started throwing up recently.
When I print the error buffer messages here:

https://github.com/jwerre/secrets/blob/a20600045fb71b7a2ffb3d5bb5b0912ff81c0ab8/lib/secrets.js#L211-L218

I printed `result.stderr.toString()`. And I get:

```
(node:29357) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
```

I'm sceptical, but this might fix the issue:
https://github.com/serverless/serverless/discussions/11750#discussioncomment-5057936

However, as a long term fix updating AWS SDK to v3 might be a good option!

**Comment by jwerre** [comment]
Ya, I'll get on this.

**Comment by jwerre** [comment]
Thanks for the heads up, I've upgraded the AWS-SDK to version 3. To use it `npm install @jwerre/secrets@2.0.1`
