### ISSUE TITLE
Could not resolve "secrets"

### ISSUE THREAD

**Issue by synthKyel** [jwerre/secrets#15]
Working on a small prototype and I did  I followed the documentation except my build manager is yarn

I did the following

`yarn add @jwerre/secrets`

The package was added successfuly on my package.json

and configured it as such
`
const Secrets = require("secrets");

const secret = new Secrets({
  region: "us-west-2",
  id: "/myenv/development/sc",
});`
`

However it seems to have a different name when imported

I have received this error

`Error: Build failed with 1 error:
src/configs/index.ts:1:24: ERROR: Could not resolve "secrets"`

**Comment by jwerre** [comment]
Sorry about that... the documentation is wrong. You need to require`@jwerre/secrets`.  I'll updated the documentation now. If you're trying to get one secret here's what that should look like.

```js
const {secretSync} = require('@jwerre/secrets');

const dbPassword = secretSync({
	region: 'us-east-2',
	id: '/my-co/development/db-password',
});
```

**Comment by synthKyel** [comment]
Thanks @jwerre  tried it now but resulted into another error. I am currently using the latest  version 

`{
    "errorType": "Runtime.UserCodeSyntaxError",
    "errorMessage": "SyntaxError: Unexpected end of JSON input",
    "stack": [
        "Runtime.UserCodeSyntaxError: SyntaxError: Unexpected end of JSON input",
        "    at _loadUserApp (file:///var/runtime/index.mjs:1084:17)",
        "    at async Object.UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1119:21)",
        "    at async start (file:///var/runtime/index.mjs:1282:23)",
        "    at async file:///var/runtime/index.mjs:1288:1"
    ]
}
`

The way it was used now is as follows

`const secret = new secretSync({
  region: "us-west-2",
  id: "/app/development/stripe",
});
console.log(secret);`

**Comment by jwerre** [comment]
Make sure your secret value is valid JSON

**Comment by synthKyel** [comment]
I double checked on AWS Secrets. I have 2 key values which as follows

`
{
   "STRIPE_API_KEY": "xxxxx",
   "STRIPE_EP_SECRET": "xxxx"
}
`

Does the library expect it to be in a different format?

**Comment by jwerre** [comment]
No, that should be fine. Anything that can be parsed with `JSON.parse`. Can you try using the CLI to get the secret:

```bash
./node_modules/.bin/get-config --env development --namespace app
```

**Comment by synthKyel** [comment]
@jwerre I got an empty JSON but my secret exists. It does not have any namespace or environment. However it was declared on the console as such

`app/development/stripe`

**Comment by jwerre** [comment]
okay... so that's the issue. Check out the readme here: https://github.com/jwerre/secrets#naming-convention

**Comment by synthKyel** [comment]
Thanks @jwerre I made some necessary changes to the naming  conventions as mentioned above using. Here's a summary however still no go.

Version I am using: 2.0.4

Secrets Name: `app/development/stripe`
Region: us-west-2
Value Inside the secret: `{"STRIPE_API_KEY":"<Value Omitted>","STRIPE_EP_SECRET":"<value_ommitted>"}`
I ran the command like what you have advised

Ran the command `get-config --env development --namespace app`
Got this result: `{"stripe":{"STRIPE_API_KEY":"<values omitted>","STRIPE_EP_SECRET":"<values omitted>"}}`

Declared it as such


```
const { secretSync } = require("@jwerre/secrets");

const secret = new secretSync({
  region: "us-west-2",
  id: "app/development/stripe",
});
```

Tried to invoke it again and this error popped up
```
{
    "errorType": "Runtime.UserCodeSyntaxError",
    "errorMessage": "SyntaxError: Unexpected end of JSON input",
    "stack": [
        "Runtime.UserCodeSyntaxError: SyntaxError: Unexpected end of JSON input",
        "    at _loadUserApp (file:///var/runtime/index.mjs:1084:17)",
        "    at async Object.UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1119:21)",
        "    at async start (file:///var/runtime/index.mjs:1282:23)",
        "    at async file:///var/runtime/index.mjs:1288:1"
    ]
}
```

**Comment by synthKyel** [comment]
I also tried the lower version 2.0.2 but still the same result

**Comment by jwerre** [comment]
hmmm... I just testing it all out on my end and it seems to be working fine. Also, all the tests are passing. What happens when you add the `raw: true` argument?

The other thing you might try is to use the `create-secrets` cli tool. This will ensure your secrets are set up correctly. Here is some pseudo code:

```bash

echo '{"stripe":{"STRIPE_API_KEY":"<values omitted>","STRIPE_EP_SECRET":"<values omitted>"}}' > ./config.json

create-secrets --region us-west-2 --env development --namespace app ./config.json

```

**Comment by synthKyel** [comment]
I tried creating a new pair of secret and still no avail. I think the library is having problem with typescript applications with esbuild in place.  I may have to give up on this library.

Added raw and this message was shown


```
{
    "errorType": "Runtime.UserCodeSyntaxError",
    "errorMessage": "SyntaxError: Unexpected end of JSON input",
    "stack": [
        "Runtime.UserCodeSyntaxError: SyntaxError: Unexpected end of JSON input",
        "    at _loadUserApp (file:///var/runtime/index.mjs:1084:17)",
        "    at async Object.UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1119:21)",
        "    at async start (file:///var/runtime/index.mjs:1282:23)",
        "    at async file:///var/runtime/index.mjs:1288:1"
    ]
}
```

Do note i am also running this inside a lambda  function so not sure if it has incompatibility problems with aws lambda

**Comment by jwerre** [comment]
Ya, I can see how that might be an issue. There are no type defs for this project; it's purely javascript. It also uses common JS rather than ES6 style modules which could be an issue for you.
