### ISSUE TITLE
getSecretSync should not return a rejected Promise when it errors.

### ISSUE THREAD

**Issue by codypotter** [jwerre/secrets#7]
I'm confused why getSecretSync would return a Promise if it is supposed to get the secrets synchronously. Should it not just return the secrets if it is a truly synchronous function?

**Comment by codypotter** [comment]
If it is the case that the promise may be immediately resolved after calling the function, then this api should be responsible for unwrapping the promise and just returning the result instead.

**Comment by jwerre** [comment]
`getSecretSync` doesn't return a Promise. It's a synchronous function and returns the secret.

https://github.com/jwerre/secrets/blob/6cfab16ae6fc0a4a456e2ca054cdbc699156e819/lib/secrets.js#L238

**Comment by codypotter** [comment]
Did you look at the documentation for that `getSecretSync`? @jwerre

**Comment by codypotter** [comment]
https://github.com/jwerre/secrets/blob/6cfab16ae6fc0a4a456e2ca054cdbc699156e819/lib/secrets.js#L200

**Comment by codypotter** [comment]
Additionally, this function does return a promise in some cases.

**Comment by jwerre** [comment]
Oh, ok. I see. That was probably just a copy paste mistake int he comment. I'll push a patch for that.

**Comment by jwerre** [comment]
After looking at your pull request I see what you're mean now @codypotter. Thanks for pointing that out, very sloppy on my part. I could see how something like that might slip by me since I don't really use the function. I'll get all this fixed up and release a new version.

**Comment by codypotter** [comment]
Awesome thanks for jumping on this 👍
